#!/usr/bin/env sh
# Install the ContextSift OpenCode plugin as a local auto-discovered plugin.
# OpenCode V2 discovers a package-style directory under ~/.config/opencode/plugins/
# with server (`index.ts`) and TUI (`tui.tsx`) entrypoints kept together.
set -eu

DIR=$(cd "$(dirname "$0")" && pwd)
PLUGINS="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/plugins"
TARGET="$PLUGINS/context-sift"

mkdir -p "$TARGET"
cat > "$TARGET/package.json" <<'EOF'
{
  "name": "context-sift-opencode",
  "type": "module",
  "exports": { ".": "./index.ts", "./tui": "./tui.tsx" }
}
EOF
cat > "$TARGET/index.ts" <<EOF
// Auto-generated by context-sift install.sh — loads the in-repo server plugin.
import plugin from "$DIR/src/index.ts"

export default plugin
EOF
cat > "$TARGET/tui.tsx" <<EOF
// Auto-generated by context-sift install.sh — loads the in-repo TUI plugin.
import plugin from "$DIR/src/tui.tsx"

export default plugin
EOF
rm -f "$PLUGINS/context-sift.ts"

echo "installed plugin: $TARGET/{package.json,index.ts,tui.tsx}"
echo "restart or reload OpenCode to activate: opencode reload"
