#!/usr/bin/env sh
# Install the ContextSift OpenCode plugin as a local auto-discovered plugin.
# OpenCode V2 loads every file under ~/.config/opencode/plugins/ automatically.
set -eu

DIR=$(cd "$(dirname "$0")" && pwd)
PLUGINS="${XDG_CONFIG_HOME:-$HOME/.config}/opencode/plugins"
TARGET="$PLUGINS/context-sift.ts"

mkdir -p "$PLUGINS"
cat > "$TARGET" <<EOF
// Auto-generated by context-sift install.sh — loads the in-repo plugin.
import plugin from "$DIR/src/index.ts"

export default plugin
EOF

echo "installed plugin shim: $TARGET"
echo "restart or reload OpenCode to activate: opencode reload"
